### ISSUE TITLE
调用notify，一直提示Invalid Signature， path这个参数 

### ISSUE THREAD

**Issue by jenchih** [mantoufan/alipay-global-sdk-php#4]

**Comment by jenchih** [comment]
index.php?s=/index/index/index
 这种获取 回调地址，一直提示签名失败，如果是  /index/index/index  这种路由，就可以签名校验成功

**Comment by mantoufan** [comment]
@jenchih 您好，`$_SERVER['REQUEST_URI']` 只有在支持 path_info 的 Web 服务器上，才会打印出完整的带参数的 URL。  
在使用前端路由，或者配置了 rewrite 伪静态的情况下，这个值可能与业务实际接收通知的 URL 不一致。  
可以先打印 `$_SERVER['REQUEST_URI']` 的值，看是否与您的预期一致，如果不一致，可以打印 `$_SERVER` 从中寻找合适的变量。或者用这些变量拼接出实际接收通知的 URL。  
```php
$notify = $alipayGlobal->getNotify(array(
  'httpMethod' => $_SERVER['REQUEST_METHOD'],
  'path' => $_SERVER['REQUEST_URI'], // 请打印 $_SERVER['REQUEST_URI'] 是否与预期一致
   'clientId' => $_SERVER['HTTP_CLIENT_ID'],
   'rsqTime' => $_SERVER['HTTP_REQUEST_TIME'],
  'rsqBody' => file_get_contents('php://input'),
  'signature' => $_SERVER['HTTP_SIGNATURE']
  ));
```
